# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Git/hdmi_video_out/hdmi_video_out.srcs/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/design_1_rgb2dvi_0_1.xci
# IP: The module: 'design_1_rgb2dvi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/hdmi_video_out/hdmi_video_out.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/hdmi_video_out/hdmi_video_out.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/hdmi_video_out/hdmi_video_out.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Git/hdmi_video_out/hdmi_video_out.srcs/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/design_1_rgb2dvi_0_1.xci
# IP: The module: 'design_1_rgb2dvi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/hdmi_video_out/hdmi_video_out.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/hdmi_video_out/hdmi_video_out.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/hdmi_video_out/hdmi_video_out.gen/sources_1/bd/design_1/ip/design_1_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
